### ISSUE TITLE
Cannot find “validator” in PlatformTextField and Capital text in PlatformText

### ISSUE THREAD

**Issue by mohammednabil95** [aqwert/flutter_platform_widgets#161]
I am using the flutter_platform_widgets package where i cannot find the validator option and why it is capital letter text while using PlatformText widget.

**Comment by aqwert** [comment]
1) The `PlatformTextField` does not have a validator since the underlying `TextField` does not have one. You probably need to use the `TextFormField`

2) The `PlatformText` by design uppercaes on android / material which is useful for uppercasing button text. If you don't want this then use flutters `Text` widget

**Comment by aqwert** [comment]
Closing as this is not part of the widgets
