### ISSUE TITLE
PlatformScaffold padding works only for AppBar

### ISSUE THREAD

**Issue by rafalolszewski94** [aqwert/flutter_platform_widgets#31]
Using `iosContentPadding: true,` is not giving padding from the bottom, so `PlatformNavBar` lays over the body:

```dart
return PlatformScaffold(
  appBar: PlatformAppBar(...),
  body: Flex(...),
  bottomNavBar: PlatformNavBar(...),
  iosContentPadding: true,
);
```

**Comment by aqwert** [comment]
Are you using a `SingleChildScrollView` or some scrolling widget?
When using a `SingleChildScrollView` the content will go under the the tab bar since that is the way iOS style works. You would need to have a widget with children (Column, Flex) with the bottom most widget a padding only for iOS. You can add the following:

```
PlatformWidget(
              ios: (_) => Container(
                    padding:
                        EdgeInsets.only(bottom: 50 + mediaQuery.padding.bottom),
                  ),
              android: (_) => Container(),
            ),
```

**Comment by aqwert** [comment]
I can add a flag to `PlatformScaffold` so that content does not go under the tabBar, though this would not give the effect of translucent under the tabBar.

**Comment by aqwert** [comment]
I have added `iosContentBottomPadding` to `PlatformScaffold` which should help.
(v 0.8.2)
