### ISSUE TITLE
Change `android` and `ios` property names to `material` and `cupertino`

### ISSUE THREAD

**Issue by wilkomanger** [aqwert/flutter_platform_widgets#59]
Especially now in the future where Flutter is also coming to web and desktop, it's perhaps better to rename all enhancment properties to the more neutral `material` and `cupertino`, just like the types which are given there (`MaterialAppBarData` for example).

```dart
final appBar = PlatformAppBar(
  title: ..,
  automaticallyImplyLeading: false,
  material: (_) => MaterialAppBarData(..),
  cupertino: (_) => CupertinoNavigationBarData(..)
);
```

This would obviously be a breaking change (major version has to be increased), but would be better. Especially if you'd make it configurable which theme is used on what platform (another issue entirely of course).

I'd be willing to do this for you by the way in a PR.

**Comment by aqwert** [comment]
Possibly.. although would there be any value in having the other platforms that can be targeted separately to that of android and ios? 

```
final appBar = PlatformAppBar(
  title: ..,
  automaticallyImplyLeading: false,
  web: (_) => MaterialAppBarData(..),  
);
```

**Comment by wilkomanger** [comment]
Perhaps, yeah. Although I think that's less of a priority. We could do both though, keep `android` and `ios`, add `web` and `desktop`, but also add `material` and `cupertino`.

Probably self-explantory but `material` and `cupertino` would be used on any platform with Material Design or Cupertino and the other properties would be platform specific.

But I still think that `material` and `cupertino` are the most important ones, the main reason the widgets are used is because of the theming, not the platform (in my experience).

**Comment by JurgenJocubeit** [comment]
I agree with @wilkomanger, in my opinion they should be renamed to match the theme they are representing. With web, at least for my use case, I'll be building a PWA (as a fallback for people that don't have or won't install my native app) with platform theme based on the user agent.

**Comment by aqwert** [comment]
My thoughts are that the main goal of this project is to style using widgets for that platform. Android is material and iOS is Cupertino. So if you are running android it will use the Material flutter widgets. When it comes to web and desktop it gets tricky because there is no specific set of widgets that target those platforms. 

One could argue that for web it defaults to using the material widgets. Example: if you used say `PlatformButton` on the web it can initially look like a material button, but with the overrides you can make it look different specifically for the web but keep the original look for android.

```
PlatformButton(
    onPressed: () => print('send'),
    child: PlatformText('Send'),
    web: (_) => WebButtonData(
            elevation: 0,
            hoverColor: Colors.red
        ),
),
```

The data object could even be moved out:

```
PlatformButton(
    onPressed: () => print('send error message'),
    child: PlatformText('Send Error'),
    web: errorButton,
),

// WebButtonData  uses Material widgets under the hood
WebButtonData errorButton = (context) => WebButtonData(
        elevation: 0,
        hoverColor: Colors.red
    );
```

If your goal is to mix an match, use cupertino on android then using this package is probably not the best approach.

**Comment by fredgrott** [comment]
yeah, I agree as web defaults to material widgets while desktop defaults to material for windows, material for linux and cupertino for mac

**Comment by aqwert** [comment]
This now has been done part of version 0.50
