### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by MrMoronIV** [aqwert/flutter_platform_widgets#69]
Can this be used in an actual project?

If not, is there an ETA of when this is possible or is this just a proof of concept? And secondly, does it not work when building an app or would it perform just fine?

In my opinion, Flutter should support this logic out of the box so I'm kinda surprised it wasn't.

**Comment by aqwert** [comment]
This library is just a thin wrapper to the material and cupertino widgets that exist and should be able to be used in production if you are willing to accept a 3rd party dependency. It originally was made to see if it was possible to create a library such as this when it started and it has just grown from there. 

Over time flutter may improve the adaptive nature of the widgets (you can see an attempt with Switch) but there will always be a difference since the platforms are structures a little differently.

**Comment by MrMoronIV** [comment]
That sounds pretty good!

Is there a place where you can put the `onsaved` parameter on a textfield for example, do all the default parameters carry over ir are they not supported as soon as they they are not mentioned in the readme?

Where would the `onsaved` go in the below example?

```
return PlatformTextField(
  android: (_) => MaterialTextFieldData(...),
  ios: (_) => CupertinoTextFieldData(...)
);
```

**Comment by aqwert** [comment]
`TextField` does not have an `onSaved`. You need to attach `TextEditingController` to the `controller` arg and likely handle the `onChanged` callback. Really depends on what your page looks like, but using `PlatformTextField` for the most part is identical than materials `TextField` or cupertino's `CupertinoTextField` widget.

The use of MaterialTextFieldData and CupertinoTextFieldData are additional arguments that are specific to the platform that the other does not support.

**Comment by MrMoronIV** [comment]
I mean `textformfield`, this one has `onsaved`. I'm sorry, Flutter is still very new to me :)

**Comment by aqwert** [comment]
This library does not include a platform `TextFormField` like there is with `TextField`. I cannot find one for ios cupertino in the flutter. If there is one I could make a `PlatformTextFormField`. If not, you could create an issue in the flutter repo to get one.
