### ISSUE TITLE
bottomNavBar in Ios

### ISSUE THREAD

**Issue by liodali** [aqwert/flutter_platform_widgets#82]
i want to make bottom nav only in Ios but when only bottomTabBar in ios,it doesn't appear

**Comment by shock-wave007** [comment]
` PlatformScaffold(
      appBar: PlatformAppBar(
        title: Text('title'),
      ),
      ios: (_)=>CupertinoPageScaffoldData(bottomTabBar:CupertinoTabBar(/* List<BottomNavigationBarItem> items*/) ),
      body: 
    );
  }`


i guess this should work

**Comment by shock-wave007** [comment]
https://github.com/aqwert/flutter_platform_widgets/issues/72#issuecomment-531204229

similar problem i guess

**Comment by aqwert** [comment]
Yes. It is a bit of a tricky one since the point of this library is that you want to have roughly the same behavour between iOS and Android but want to look as native as possible. If you want iOS to have bottom tabs and Android not then it may be better to just use the material and cupertino widgets directly. You can on the Scaffold's body use `PlatformWidget`to switch between the two
